version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.sqlite3
      - DJANGO_DB_NAME=mydatabase
      - DJANGO_DB_USER=mydatabaseuser
      - DJANGO_DB_PASSWORD=mypassword
      - DJANGO_DB_HOST=db
