# Generated by Django 5.0 on 2024-01-04 23:13

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_all_users', models.BooleanField(default=False)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_group_groups', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=350, unique=True)),
                ('cover_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos')),
                ('hightlight', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('groups', models.ManyToManyField(through='blog.ArticleGroup', to='auth.group')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.AddField(
            model_name='articlegroup',
            name='articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_group_articles', to='blog.articles'),
        ),
    ]
