# Generated by Django 3.2.23 on 2024-01-07 18:10

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=350, unique=True)),
                ('cover_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos')),
                ('hightlight', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('is_all_users', models.BooleanField(default=False)),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
